name: check docs build

on:
  pull_request:
    branches:
      - main
  schedule:
    # 03:00 every Saturday morning
    - cron: '0 3 * * 6'

jobs:
  check:
    name: check docs build
    runs-on: ubuntu-22.04
    steps:
    uses: actions/checkout@v5
    with:
      submodules: true
      fetch-depth: '0'
    name: Install uv
    uses: astral-sh/setup-uv@v7
    with:
        enable-cache: true
        ersion: "0.10.9"
    uses: extractions/setup-just@v3
    with:
      just-version: 1.5.0
    name: install graphviz
    run: |
          sudo apt-get update
          sudo apt-get install graphviz
    name: build manual and examples
    run: |
        just build
